---
- hosts: localhost
  vars_files:
    - vars.yaml
  tasks:
    - name: create user
      community.aws.iam_user:
        name: "{{ iam_user }}"
        managed_policies:
          - arn:aws:iam::aws:policy/AdministratorAccess
        state: present
    - name: create user's key
      shell: 'aws iam create-access-key --user-name "{{ iam_user }}" > key.txt'

    - amazon.aws.s3_bucket:
        name: "{{ bucket }}"
        state: present
